version: '3.7'

services:
  nginx:
    image: nginx:1.22.0
    environment:
      - SERVER_NAME="${SERVER_NAME}"
    ports:
      - "4443:4443"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./nginx/docker-entrypoint.d/:/docker-entrypoint.d/
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/docker-entrypoint.sh"
    command: ["nginx"]

  certbot:
    image: certbot/certbot:v1.32.0
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  
  doichain:
    image: "doichain/core:dc0.20.1.12" 
    container_name: doichain
    hostname: doichain
    ports:
      - "8339:8339"
    volumes:
      - doichain-volume:/home/doichain/data
    environment:
      - RPC_PASSWORD=password
      - RPC_ALLOW_IP=0.0.0.0/0 #::/0
    stdin_open: true
    tty: true
    networks:
      static-network:
       ipv4_address: 172.20.0.6

  dapp: 
    image: doichain/dapp
    container_name: dapp
    hostname: dapp
 #   build: ./dapp
    ports:
      - "3000:3000"
    volumes:
      - dapp-volume:/home/doichain/data
    environment:
      - DOICHAIN_DAPP_VER=v0.0.9.114
      - MONGO_URL="mongodb://mongo:27017"
      - DAPP_HOST="${SERVER_NAME}"    
      - DAPP_PORT=3000
      - RPC_HOST=doichain 
      - RPC_PORT=8339   
      - RPC_USER="${RPC_USER}"
      - RPC_PASSWORD="${RPC_PASSWORD}"
      - DAPP_SMTP_USER="${DAPP_SMTP_USER}"
      - DAPP_SMTP_HOST="${DAPP_SMTP_HOST}"
      - DAPP_SMTP_PASS="${DAPP_SMTP_PASS}"
      - DAPP_SMTP_PORT="${DAPP_SMTP_PORT}"
      - DAPP_SMTP_DEFAULT_FROM="${DAPP_SMTP_DEFAULT_FROM}"

regtest-mongo:
  image: "mongo:3.2"
  container_name: mongo
  hostname: mongo
  expose:
    - "27017"
  ports:
    - "28017:27017"
  volumes: 
    -  mongo-volume:/data
  networks:
    static-network:
      ipv4_address: 172.20.0.9

volumes:
  bitcoin-volume:
  doichain-volume:
  dapp-volume:
  mongo-volume:

networks:
  static-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16