version: '3.7'

services:
  doichain:
    image: "doichain/node-only:dc0.20.1.11_1" 
    hostname: doichain
    ports:
      - "8339:8339"
    environment:
      - RPC_PASSWORD=password
      - RPC_ALLOW_IP=0.0.0.0/0 #::/0
    #  - REGTEST=true
    #  - CONNECTION_NODE=altbob 
#    dns_search: ci-doichain.org
#    volumes:
#      - ../scripts/docker-compose/resolv.conf:/etc/resolv.conf
    stdin_open: true
    tty: true
    networks:
      static-network:
        ipv4_address: 172.20.0.6

  dapp:
    hostname: dapp
    image: doichain/dapp
    build: .
    ports:
      - "3000:3000"
    environment:
      - DOICHAIN_DAPP_VER=v0.0.9.114
      - MONGO_URL="mongodb://mongo:27017"
      - DAPP_HOST=localhost    
      - DAPP_PORT=3000
      - RPC_HOST=doichain 
      - RPC_PORT=8339   
      - RPC_USER=admin
      - RPC_PASSWORD=password
      - DAPP_SMTP_USER=doichain
      - DAPP_SMTP_HOST=smtp
      - DAPP_SMTP_PASS=doichain
      - DAPP_SMTP_PORT=587
      - DAPP_SMTP_DEFAULT_FROM=validator@doichain.org
    # stdin_open: true
    # tty: true
    networks:
      static-network:
        ipv4_address: 172.20.0.7

  regtest-mongo:
      image: "mongo:3.2"
      hostname: mongo
      expose:
        - "27017"
      ports:
        - "28017:27017"
      networks:
        static-network:
          ipv4_address: 172.20.0.8
  
networks:
  static-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
        